name: go

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/go.yml
      - main.go
      - go.sum
      - go.mod
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build main.go
